"""Auto-generated by WLAN Test GUI.

EAP111-MFG: full EAP111 manufacturing (FDL) flow. Step order follows the
reference PASS log (docs/logfiles/EAP111_T_PASS_Y_V4.1.1.1F.1.2_093645.txt).
Certification steps are backend STUBs for now.
"""
import time
from mfg.manufacturing_script import ManufacturingScript


class TestCase(ManufacturingScript):
    tc_id = "EAP111-MFG"
    station = "FDL"
    headline = "EAP111-MFG"
    purpose = "EAP111 full manufacturing flow (barcode -> flash -> MFG data -> cert -> verify)"

    def run(self):
        try:
            # 0. Scan SN + MAC (two scans, any order; auto-detected).
            self.scan_barcode(source="usb_hid", timeout=30, expected_len=12)
            # 1. Enter U-Boot menu (DC OFF->ON, interrupt autoboot)
            self.enter_uboot_menu()
            # 2. Read HW version (MAC/SN/Model/HW Rev) from factory MTD
            self.read_hw_version()
            time.sleep(5)
            # 3. TFTP download + flash FIP and firmware images
            self.update_flash_image()
            # 4. Write U-Boot env: bootcount/active/upgrade_available/SN
            self.write_uboot_env_serial()
            # 5. Write manufacturing data env vars (MAC & SN)
            self.write_manufacturing_data(mac_address="44:45:BA:03:10:D8")
            # 6. Enter TIP kernel (first Linux boot)
            self.enter_tip_kernel()
            # 7. Check TIP version
            self.check_tip_version()
            # 8. Check manufacturing data (jffs2reset+reboot -> U-Boot verify)
            self.check_manufacturing_data()
            # 9. Reboot & wait login (second Linux boot)
            self.enter_tip_kernel_2()
            # 10. Reset to default
            self.reset_default()
            # 11-13. Certification (STUB)
            self.prepare_certification(cert_server="prod-cert.accton.com")
            self.write_certification(dut_ip="192.168.1.20")
            self.check_certification()

            self.message("PASS")
        finally:
            self.cleanup()
